Repository ultralytics/flickr_scraper, pull requests merged in 2025-01, with the labels that each got.

#39 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#40 Standardize license headers in Python files
  flickr_scraper.py
  utils/clean_images.py
  utils/flickr_scraper_noapi.py
  utils/general.py
  utils/multithread_example.py
Labels: documentation

#41 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
Labels: documentation, devops
